@host=http://localhost:3200

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstname":"zeeshan",
    "lastname":"Asghar",
    "email":"zeeshan@live.com",
    "password":"XXYYZZ@1122"
}

###

POST  {{host}}/auth/login
Content-Type: application/json

{
   "email":"zeeshan1@live.com",
    "password":"XXYYZZ@1122"
}
 
